[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/aev_plig", "src/torchani_mod"]

[project]
name = "aev-plig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biopandas>=0.5.1",
    "importlib-metadata",
    "lark",
    "pandas",
    "qcelemental",
    "rdkit",
    "scikit-learn",
    "torch",
    "torch-geometric",
    "torch-scatter",
    "torchani",
]

[tool.uv.extra-build-dependencies]
torch-scatter = ["torch"]


[tool.setuptools.package-data]
aev-plig = ["data/PDB_Atom_Keys.csv"]